version: '3.4' #Minimun version supporting target property

services:
  app:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Anonymous volume to prevent existing node_modules in container to be overridden
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - NODE_ENV=docker
    command: yarn start:debug

  db:
    container_name: postgres
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=taskmanagement
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:
