version: '3.4' #Minimun version supporting target property

services:
  app:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Anonymous volume to prevent existing node_modules in container to be overridden
    ports:
      - 3000:3000
      - 9229:9229
    env_file:
      - docker.env
    command: yarn start:dev
    depends_on:
      - db

  db:
    container_name: postgres
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    env_file:
      - docker.env
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:
