server:
  port: 'PORT'

db:
  host: 'RDS_HOSTNAME'
  port: 'RDS_PORT'
  username: 'RDS_USERNAME'
  password: 'RDS_PASSWORD'
  database: 'RDS_DB_NAME'
  synchronize: 'TYPEORM_SYNC'

jwt:
  secret: 'JWT_SECRET'
