server:
  port: 3001
  origin: 'http://localhost:3000'

db:
  type: 'postgres'
  url: 'postgres://postgres:postgres@localhost:5432/taskmanagement'
  synchronize: true

jwt:
  secret: 'secret'
  expiresIn: 3600
